# Generated by Django 4.1 on 2022-10-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hawkerapp", "0004_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="owner",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
