# Generated by Django 4.1 on 2022-10-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hawkerapp", "0002_rename_first_name_hawkerowner_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stall", name="owner", field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(name="HawkerOwner",),
    ]
