# Generated by Django 4.1 on 2022-10-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hawkerapp", "0008_alter_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="description",
            field=models.TextField(default=None),
        ),
    ]
