# Generated by Django 4.1 on 2022-10-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hawkerapp", "0011_remove_review_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="photo",
            field=models.ImageField(default=0, upload_to="images"),
        ),
    ]
