# Generated by Django 4.1 on 2022-10-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hawkerapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hawkerowner", old_name="first_name", new_name="name",
        ),
        migrations.RemoveField(model_name="hawkerowner", name="last_name",),
        migrations.AlterField(
            model_name="stall",
            name="foods",
            field=models.ManyToManyField(related_name="stalls", to="hawkerapp.food"),
        ),
    ]
