# Generated by Django 4.1 on 2022-10-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hawkerapp", "0005_review_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
