# Generated by Django 4.1 on 2022-10-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hawkerapp", "0009_review_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="photo",
            field=models.ImageField(default=None, upload_to="images"),
        ),
    ]
