# Generated by Django 4.1 on 2022-10-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hawkerapp", "0015_remove_location_photo_remove_review_photo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="stall",
            name="menus",
            field=models.ManyToManyField(related_name="stallss", to="hawkerapp.menu"),
        ),
    ]
