# Generated by Django 4.1 on 2022-10-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hawkerapp", "0016_menu_stall_menus"),
    ]

    operations = [
        migrations.RemoveField(model_name="stall", name="foods",),
        migrations.AlterField(
            model_name="stall",
            name="menus",
            field=models.ManyToManyField(related_name="stalls", to="hawkerapp.menu"),
        ),
        migrations.DeleteModel(name="Food",),
    ]
